/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class systemdashboard_SystemMonitor */

#ifndef _Included_systemdashboard_SystemMonitor
#define _Included_systemdashboard_SystemMonitor
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     systemdashboard_SystemMonitor
 * Method:    getCpuUsage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_systemdashboard_SystemMonitor_getCpuUsage
  (JNIEnv *, jobject);

/*
 * Class:     systemdashboard_SystemMonitor
 * Method:    getTotalMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_systemdashboard_SystemMonitor_getTotalMemory
  (JNIEnv *, jobject);

/*
 * Class:     systemdashboard_SystemMonitor
 * Method:    getFreeMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_systemdashboard_SystemMonitor_getFreeMemory
  (JNIEnv *, jobject);

/*
 * Class:     systemdashboard_SystemMonitor
 * Method:    getTotalDiskSpace
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_systemdashboard_SystemMonitor_getTotalDiskSpace
  (JNIEnv *, jobject);

/*
 * Class:     systemdashboard_SystemMonitor
 * Method:    getFreeDiskSpace
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_systemdashboard_SystemMonitor_getFreeDiskSpace
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif 